#!/bin/bash

pacman -Sy
pacman -S --noconfirm --needed git
if [ ! -d bootstrap ]; then
    until git clone https://dnlcorrea43@bitbucket.org/dnlcorrea43/bootstrap.git; do
	echo Trying again
    done
fi

cd bootstrap

echo Start with arch.sh
