#!/bin/bash

pacman -Sy
pacman -S --noconfirm --needed git
if [ ! -d .dot ]; then
    until git clone --depth 1 https://dnlcorrea@github.com/dnlcorrea/dot.git .dot; do
	echo Trying again
    done
fi

cd .dot/bootstrap

echo Start with arch.sh
